name: first-workflow
on: [push]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hellow
        run: echo "Hello World"
      - name: multiple lime cmd
        run: |
          node -v
          npm -v